apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    database: energy
    user: root
    jsonData:
      httpMode: GET
    secureJsonData:
      password: $INFLUXDB_PASS
